import type { Test } from '@lvce-editor/test-with-playwright'

export const name = 'viewlet.csv-save'

export const test: Test = async ({ Dialog, expect, FileSystem, KeyBoard, Locator, Main }) => {
  console.log('CSV-save checkpoint: const tmpDir = await FileSystem.getTmpDir({ scheme: file })')
  const tmpDir = await FileSystem.getTmpDir({ scheme: 'file' })
  const uri = `${tmpDir}/save.csv`
  const original = 'name,quantity,note\nApple,10,red\nPear,,green\nPlum,30,purple\n'
  console.log('CSV-save checkpoint: await FileSystem.writeFile(uri, original)')
  await FileSystem.writeFile(uri, original)
  console.log('CSV-save checkpoint: await Main.openUri(uri)')
  await Main.openUri(uri)
  const tab = Locator('.MainTab[title$="save.csv"]')
  const dirtyTab = Locator('.MainTab.MainTabModified[title$="save.csv"]')
  const cell = Locator('[id="cell:0:2"]')
  const editor = Locator('[name="cellEditor"]')
  console.log('CSV-save checkpoint: await expect(cell).toHaveText(10)')
  await expect(cell).toHaveText('10')
  const edit = async (row: number, value: string): Promise<void> => {
    console.log(
      'CSV-save checkpoint: await Locator([id="cell:row}:2"]).dispatchEvent(dblclick, { bubbles: true } as unknown as string)',
    )
    await Locator(`[id="cell:${row}:2"]`).dispatchEvent('dblclick', { bubbles: true } as unknown as string)
    console.log('CSV-save checkpoint: await expect(editor).toBeFocused()')
    await expect(editor).toBeFocused()
    console.log('CSV-save checkpoint: await editor.type(value)')
    await editor.type(value)
    console.log('CSV-save checkpoint: await KeyBoard.press(Enter)')
    await KeyBoard.press('Enter')
    console.log('CSV-save checkpoint: await expect(editor).toHaveCount(0)')
    await expect(editor).toHaveCount(0)
    console.log('CSV-save checkpoint: await expect(tab).toHaveClass(MainTabModified)')
    await expect(tab).toHaveClass('MainTabModified')
  }
  const assertDisk = async (expected: string): Promise<void> => {
    const actual = await FileSystem.readFile(uri)
    if (actual !== expected) throw new Error(`Unexpected CSV bytes: ${JSON.stringify(actual)}`)
  }

  console.log('CSV-save checkpoint: await edit(0, 15)')
  await edit(0, '15')
  console.log('CSV-save checkpoint: await assertDisk(original)')
  await assertDisk(original)
  console.log('CSV-save checkpoint: await Dialog.mockConfirm(() => false)')
  await Dialog.mockConfirm(() => false)
  console.log('CSV-save checkpoint: await Main.closeActiveEditor()')
  await Main.closeActiveEditor()
  console.log('CSV-save checkpoint: await expect(tab).toBeVisible()')
  await expect(tab).toBeVisible()
  console.log('CSV-save checkpoint: await expect(cell).toHaveText(15)')
  await expect(cell).toHaveText('15')

  console.log('CSV-save checkpoint: await KeyBoard.press(Control+s)')
  await KeyBoard.press('Control+s')
  console.log('CSV-save checkpoint: await expect(dirtyTab).toHaveCount(0)')
  await expect(dirtyTab).toHaveCount(0)
  const replaced = original.replace('Apple,10,', 'Apple,15,')
  console.log('CSV-save checkpoint: await assertDisk(replaced)')
  await assertDisk(replaced)
  console.log('CSV-save checkpoint: await Main.closeActiveEditor()')
  await Main.closeActiveEditor()
  console.log('CSV-save checkpoint: await Main.openUri(uri)')
  await Main.openUri(uri)
  console.log('CSV-save checkpoint: await expect(cell).toHaveText(15)')
  await expect(cell).toHaveText('15')

  console.log('CSV-save checkpoint: await edit(1, 42)')
  await edit(1, '42')
  console.log('CSV-save checkpoint: await Locator(.TitleBarTopLevelEntry, { hasText: File }).click()')
  await Locator('.TitleBarTopLevelEntry', { hasText: 'File' }).click()
  console.log('CSV-save checkpoint: await expect(Locator(.Menu)).toBeVisible()')
  await expect(Locator('.Menu')).toBeVisible()
  console.log('CSV-save checkpoint: await Locator(.MenuItem, { hasText: Save }).nth(0).click()')
  await Locator('.MenuItem', { hasText: 'Save' }).nth(0).click()
  const filled = replaced.replace('Pear,,', 'Pear,42,')
  console.log('CSV-save checkpoint: await expect(dirtyTab).toHaveCount(0)')
  await expect(dirtyTab).toHaveCount(0)
  console.log('CSV-save checkpoint: await assertDisk(filled)')
  await assertDisk(filled)
  console.log('CSV-save checkpoint: await edit(0, )')
  await edit(0, '')
  console.log('CSV-save checkpoint: await Locator(.TitleBarTopLevelEntry, { hasText: File }).click()')
  await Locator('.TitleBarTopLevelEntry', { hasText: 'File' }).click()
  console.log('CSV-save checkpoint: await expect(Locator(.Menu)).toBeVisible()')
  await expect(Locator('.Menu')).toBeVisible()
  console.log('CSV-save checkpoint: await Locator(.MenuItem, { hasText: Save All }).click()')
  await Locator('.MenuItem', { hasText: 'Save All' }).click()
  const cleared = filled.replace('Apple,15,', 'Apple,,')
  console.log('CSV-save checkpoint: await expect(dirtyTab).toHaveCount(0)')
  await expect(dirtyTab).toHaveCount(0)
  console.log('CSV-save checkpoint: await assertDisk(cleared)')
  await assertDisk(cleared)
  console.log('CSV-save checkpoint: await Main.closeActiveEditor()')
  await Main.closeActiveEditor()
  console.log('CSV-save checkpoint: await Main.openUri(uri)')
  await Main.openUri(uri)
  console.log('CSV-save checkpoint: await expect(cell).toHaveText()')
  await expect(cell).toHaveText('')
  console.log('CSV-save checkpoint: await expect(Locator([id="cell:1:2"])).toHaveText(42)')
  await expect(Locator('[id="cell:1:2"]')).toHaveText('42')
  console.log('CSV-save checkpoint: await expect(Locator([id="cell:0:1"])).toHaveText(Apple)')
  await expect(Locator('[id="cell:0:1"]')).toHaveText('Apple')
  console.log('CSV-save checkpoint: await expect(Locator([id="cell:0:3"])).toHaveText(red)')
  await expect(Locator('[id="cell:0:3"]')).toHaveText('red')

  console.log('CSV-save checkpoint: await cell.dispatchEvent(dblclick, { bubbles: true } as unknown as string)')
  await cell.dispatchEvent('dblclick', { bubbles: true } as unknown as string)
  console.log('CSV-save checkpoint: await expect(editor).toBeFocused()')
  await expect(editor).toBeFocused()
  console.log('CSV-save checkpoint: await editor.type(cancelled)')
  await editor.type('cancelled')
  console.log('CSV-save checkpoint: await KeyBoard.press(Escape)')
  await KeyBoard.press('Escape')
  console.log('CSV-save checkpoint: await expect(cell).toHaveText()')
  await expect(cell).toHaveText('')
  console.log('CSV-save checkpoint: await expect(dirtyTab).toHaveCount(0)')
  await expect(dirtyTab).toHaveCount(0)
  console.log('CSV-save checkpoint: await assertDisk(cleared)')
  await assertDisk(cleared)
}
